services:
    # Serviço da Aplicação Laravel (PHP-FPM)
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel-network

    # Serviço do Servidor Web (Nginx)
    nginx:
        image: nginx:stable-alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-network
        depends_on:
            - app

    # Serviço do Banco de Dados (MySQL)
    db:
        image: mysql:8.0
        container_name: laravel-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel-network
        ports:
            - "3306:3306"

    # Serviço do Redis (Opcional, mas recomendado para cache e filas)
    redis:
        image: redis:alpine
        container_name: laravel-redis
        restart: unless-stopped
        networks:
            - laravel-network
        ports:
            - "6379:6379"

# Redes
networks:
    laravel-network:
        driver: bridge

# Volumes
volumes:
    dbdata:
        driver: local
